# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.front_base_url: "http://localhost:3000"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $sender_email: "%env(SENDER_MAIL)%"
      $frontBaseUrl: "%app.front_base_url%"

  # Services métier
  App\Service\EventService:
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"
      $giftListRepository: '@App\Repository\GiftListRepository'

  App\Service\InvitationService:
    arguments:
      $invitationRepository: '@App\Repository\InvitationRepository'
      $entityManager: "@doctrine.orm.entity_manager"
      $tokenGenerator: "@security.csrf.token_generator"
      $mailerService: '@App\Service\MailerService'
      $eventService: '@App\Service\EventService'
      $frontBaseUrl: "%app.front_base_url%"

  App\Service\SantaService:
    arguments:
      $santaRepository: '@App\Repository\SantaRepository'
      $entityManager: "@doctrine.orm.entity_manager"

  App\Service\EventValidationService:
    arguments:
      $validator: "@validator"

      # Si vous n'avez pas encore de EventVoter, voici un exemple
  App\Security\EventVoter:
    tags:
      - { name: security.voter }

      # Configuration du MailerService s'il n'existe pas déjà
  App\Service\MailerService:
    arguments:
      $twig: "@twig"

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Security\AbstractOAuthAuthenticator:
    abstract: true
    arguments:
      $clientRegistry: '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
      $userRepository: '@App\Repository\UserRepository'
      $registrationService: '@App\Security\OAuthRegistrationService'
      $jwtManager: "@lexik_jwt_authentication.jwt_manager"
      $eventDispatcher: "@event_dispatcher"

  App\Security\GoogleAuthenticator:
    parent: App\Security\AbstractOAuthAuthenticator
