<?php

namespace ContainerLDxIuN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LFyiK0hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lFyiK0h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lFyiK0h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\AdminController::updateUser' => ['privates', '.service_locator.J7rxUVe', 'get_ServiceLocator_J7rxUVeService', true],
            'App\\Controller\\AdminController::userDetail' => ['privates', '.service_locator.LJ7T6QG', 'get_ServiceLocator_LJ7T6QGService', true],
            'App\\Controller\\AdminController::userList' => ['privates', '.service_locator.LJ7T6QG', 'get_ServiceLocator_LJ7T6QGService', true],
            'App\\Controller\\GiftController::createGift' => ['privates', '.service_locator.AEfQEVz', 'get_ServiceLocator_AEfQEVzService', true],
            'App\\Controller\\GiftController::deleteGift' => ['privates', '.service_locator.3KgJCcu', 'get_ServiceLocator_3KgJCcuService', true],
            'App\\Controller\\GiftController::getGift' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\GiftController::updateGift' => ['privates', '.service_locator.5ixanV5', 'get_ServiceLocator_5ixanV5Service', true],
            'App\\Controller\\RegisterController::createUser' => ['privates', '.service_locator.8ce0SQ8', 'get_ServiceLocator_8ce0SQ8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.djBiB42', 'get_ServiceLocator_DjBiB42Service', true],
            'App\\Controller\\AdminController:updateUser' => ['privates', '.service_locator.J7rxUVe', 'get_ServiceLocator_J7rxUVeService', true],
            'App\\Controller\\AdminController:userDetail' => ['privates', '.service_locator.LJ7T6QG', 'get_ServiceLocator_LJ7T6QGService', true],
            'App\\Controller\\AdminController:userList' => ['privates', '.service_locator.LJ7T6QG', 'get_ServiceLocator_LJ7T6QGService', true],
            'App\\Controller\\GiftController:createGift' => ['privates', '.service_locator.AEfQEVz', 'get_ServiceLocator_AEfQEVzService', true],
            'App\\Controller\\GiftController:deleteGift' => ['privates', '.service_locator.3KgJCcu', 'get_ServiceLocator_3KgJCcuService', true],
            'App\\Controller\\GiftController:getGift' => ['privates', '.service_locator.iWwbKUs', 'get_ServiceLocator_IWwbKUsService', true],
            'App\\Controller\\GiftController:updateGift' => ['privates', '.service_locator.5ixanV5', 'get_ServiceLocator_5ixanV5Service', true],
            'App\\Controller\\RegisterController:createUser' => ['privates', '.service_locator.8ce0SQ8', 'get_ServiceLocator_8ce0SQ8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::updateUser' => '?',
            'App\\Controller\\AdminController::userDetail' => '?',
            'App\\Controller\\AdminController::userList' => '?',
            'App\\Controller\\GiftController::createGift' => '?',
            'App\\Controller\\GiftController::deleteGift' => '?',
            'App\\Controller\\GiftController::getGift' => '?',
            'App\\Controller\\GiftController::updateGift' => '?',
            'App\\Controller\\RegisterController::createUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:updateUser' => '?',
            'App\\Controller\\AdminController:userDetail' => '?',
            'App\\Controller\\AdminController:userList' => '?',
            'App\\Controller\\GiftController:createGift' => '?',
            'App\\Controller\\GiftController:deleteGift' => '?',
            'App\\Controller\\GiftController:getGift' => '?',
            'App\\Controller\\GiftController:updateGift' => '?',
            'App\\Controller\\RegisterController:createUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
